debug: true

summary_model: gpt-4o-mini

models:
  gpt-4o-mini:
    api_type: openai
    base_url: https://newapi.deepwisdom.ai/v1
    api_key: sk-wXZCvZmM1Ur0rG5iYk7fu7Ek6OC9EzvxcL7qNRWjlyMJQ1Fb
  gemini-2.5-flash:
    api_type: openai
    base_url: https://newapi.deepwisdom.ai/v1
    api_key: sk-wXZCvZmM1Ur0rG5iYk7fu7Ek6OC9EzvxcL7qNRWjlyMJQ1Fb
    cost:
      input_cost_per_token: 0.0000003
      output_cost_per_token: 0.00000252
      max_tokens: 8192
      max_input_tokens: 1048576
      max_output_tokens: 8192
  gemini-3-pro-preview:
    api_type: openai
    base_url: https://newapi.deepwisdom.ai/v1
    api_key: sk-wXZCvZmM1Ur0rG5iYk7fu7Ek6OC9EzvxcL7qNRWjlyMJQ1Fb
    cost:
      input_cost_per_token: 0.00000125
      output_cost_per_token: 0.00001
      max_tokens: 65536
      max_input_tokens: 1048576
      max_output_tokens: 65536

daytona:
  api_key: dtn_20f1d7ba91a3852a85824943e968c5202b6abb8b6f144c06cf20ae6c6cbca7c3
  api_url: https://app.daytona.io/api

e2b:
  api_key: "e2b_8b5699badad409948b1efd4683406adfef161859"

ppio:
  api_key: "sk_Y0LUPeUzm0bLIJ0FmpRXdGuRkoBORDuuRXV7F1HC5T0"
  template: "base"